cache:
  paths:
      - vendor/
before_script:
- apt-get update -yqq
- apt-get install git  -yqq
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install
- ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1

test:5.4:
  image: php:5.4
  script:
  - ./vendor/bin/phpcs --standard=psr2 src/
  - ./vendor/bin/peridot test/
test:5.4:
  image: php:5.5
  script:
  - ./vendor/bin/phpcs --standard=psr2 src/    
  - ./vendor/bin/peridot test
test:5.6:
  image: php:5.6
  script:
  - ./vendor/bin/phpcs --standard=psr2 src/    
  - ./vendor/bin/peridot test
test:7.0:
  image: php:7.0
  script:
  - ./vendor/bin/phpcs --standard=psr2 src/    
  - ./vendor/bin/peridot test
test:7.1:
  image: php:7.1
  script:
  - ./vendor/bin/phpcs --standard=psr2 src/    
  - ./vendor/bin/peridot test
test:7.2:
  image: php:7.2
  script:
  - ./vendor/bin/phpcs --standard=psr2 src/    
  - ./vendor/bin/peridot test
