dist: trusty
language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- hhvm
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
- composer self-update
- composer install
- ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
script:
- ./vendor/bin/phpcs --standard=psr2 src/
- ./vendor/bin/peridot test/