version: "{branch}-{build}"
build: false
clone_folder: C:\projects\ng-upload-chunked

install:
  - cinst -y php --version 7.0.27 --ignore-dependencies
  - cd c:\tools\php70
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - SET PATH=C:\tools\php70;%PATH%
  - cd C:\projects\ng-upload-chunked
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install
  - vendor\bin\phpcs.bat --config-set ignore_warnings_on_exit 1

test_script:
  - cd C:\projects\ng-upload-chunked
  - vendor\bin\phpcs.bat --standard=psr2 src/
  - vendor\bin\peridot.bat test/
